//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperManagerChatBot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopicDetail
    {
        public string ID { get; set; }
        public string TopicID { get; set; }
        public string TopicDetail1 { get; set; }
        public string ParentTopicID { get; set; }
        public string BotReplyMessage { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    }
}
